"""Add tokens and execution_id to messages

Revision ID: 3cf4b14d599b
Revises: 091c1827c5ad
Create Date: 2026-03-13 05:05:20.795885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf4b14d599b'
down_revision = '091c1827c5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
