"""Add tokens and execution_id to messages

Revision ID: 3cf4b14d599b
Revises: 091c1827c5ad
Create Date: 2026-03-13 05:05:20.795885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf4b14d599b'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('execution_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_messages_execution_id'), 'messages', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_execution_id'), table_name='messages')
    op.drop_column('messages', 'tokens_used')
    op.drop_column('messages', 'execution_id')
    # ### end Alembic commands ###
